//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetStarter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetStarter.Resources.HomePageResource", typeof(HomePageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Account.
        /// </summary>
        public static string AnAccount {
            get {
                return ResourceManager.GetString("AnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As Many As You Want.
        /// </summary>
        public static string AsManyAsYouWant {
            get {
                return ResourceManager.GetString("AsManyAsYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone this project. Then... Yes! You have several projects ready with some existing features..
        /// </summary>
        public static string AsManyAsYouWantDescription {
            get {
                return ResourceManager.GetString("AsManyAsYouWantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC C# Web Application.
        /// </summary>
        public static string ASPNETMVCWebApplication {
            get {
                return ResourceManager.GetString("ASPNETMVCWebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        public static string Benefits {
            get {
                return ResourceManager.GetString("Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap HTML Website Templates.
        /// </summary>
        public static string BootstrapHTMLWebsiteTemplates {
            get {
                return ResourceManager.GetString("BootstrapHTMLWebsiteTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirmpassword {
            get {
                return ResourceManager.GetString("Confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRUD Users.
        /// </summary>
        public static string CRUDUsers {
            get {
                return ResourceManager.GetString("CRUDUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Documentation.
        /// </summary>
        public static string DetailedDocumentation {
            get {
                return ResourceManager.GetString("DetailedDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envato Portfolio.
        /// </summary>
        public static string EnvatoPortfolio {
            get {
                return ResourceManager.GetString("EnvatoPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, it&apos;s in our plan, but for now, we couldn&apos;t guarantee the release time..
        /// </summary>
        public static string FAQFourAnswer {
            get {
                return ResourceManager.GetString("FAQFourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can you create a .NET Core MVC version?.
        /// </summary>
        public static string FAQFourQuestion {
            get {
                return ResourceManager.GetString("FAQFourQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We only provide support for fixing existing bugs in the templates and answering questions regarding the existing features. Step-by-step guidance on how to do your custom modifications, how to solve bugs after your own modifications and direct installation are not part of our support. Thank you so much for your understanding. We will spend our time to create more amazing templates for you..
        /// </summary>
        public static string FAQOneAnswer {
            get {
                return ResourceManager.GetString("FAQOneAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the support policy?.
        /// </summary>
        public static string FAQOneQuestion {
            get {
                return ResourceManager.GetString("FAQOneQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, you can. Go to &quot;/Views/Shared/_FooterBeforeLogin.cshtml&quot; and find the footer section to edit or remove the copyright text..
        /// </summary>
        public static string FAQThreeAnswer {
            get {
                return ResourceManager.GetString("FAQThreeAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can I edit or remove the Copyright text at the footer?.
        /// </summary>
        public static string FAQThreeQuestion {
            get {
                return ResourceManager.GetString("FAQThreeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer is: Immediately after purchase. You could read.
        /// </summary>
        public static string FAQTwoAnswerPartOne {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for more information, there is “Downloading your items” section at the end of this article..
        /// </summary>
        public static string FAQTwoAnswerPartTwo {
            get {
                return ResourceManager.GetString("FAQTwoAnswerPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When can I download the file after purchase the item?.
        /// </summary>
        public static string FAQTwoQuestion {
            get {
                return ResourceManager.GetString("FAQTwoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Essential Features Needed To Start A ASP.NET MVC Web App Project.
        /// </summary>
        public static string FeaturesDescription {
            get {
                return ResourceManager.GetString("FeaturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill your details to register..
        /// </summary>
        public static string Fillyourdetailstoregister {
            get {
                return ResourceManager.GetString("Fillyourdetailstoregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill your username and password to sign in..
        /// </summary>
        public static string Fillyourusernameandpasswordtosignin {
            get {
                return ResourceManager.GetString("Fillyourusernameandpasswordtosignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow our social media to get updates or news about the projects..
        /// </summary>
        public static string FollowUsDescription {
            get {
                return ResourceManager.GetString("FollowUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2022 AuraTheme. All Rights Reserved..
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string Forgotyourpassword {
            get {
                return ResourceManager.GetString("Forgotyourpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("FrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Source Code.
        /// </summary>
        public static string FullSourceCode {
            get {
                return ResourceManager.GetString("FullSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully Responsive.
        /// </summary>
        public static string FullyResponsive {
            get {
                return ResourceManager.GetString("FullyResponsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a ASP.NET MVC C# Web Application with .NET Framework. It helps to kick start your project with some essential modules.
        /// </summary>
        public static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetStarter- ASP.NET MVC C# Web Application Starter Template.
        /// </summary>
        public static string HomeIndexTabTitle {
            get {
                return ResourceManager.GetString("HomeIndexTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your .net project easily with.
        /// </summary>
        public static string HomeTitleOne {
            get {
                return ResourceManager.GetString("HomeTitleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to template.
        /// </summary>
        public static string HomeTitleTwo {
            get {
                return ResourceManager.GetString("HomeTitleTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &amp; Export.
        /// </summary>
        public static string ImportAndExport {
            get {
                return ResourceManager.GetString("ImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Home Page.
        /// </summary>
        public static string IncludeHomePage {
            get {
                return ResourceManager.GetString("IncludeHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not only get the admin dashboard, but also a standard home page design like this one..
        /// </summary>
        public static string IncludeHomePageDescription {
            get {
                return ResourceManager.GetString("IncludeHomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetStarter FAQ Articles.
        /// </summary>
        public static string NetStarterFAQArticles {
            get {
                return ResourceManager.GetString("NetStarterFAQArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        public static string OurProducts {
            get {
                return ResourceManager.GetString("OurProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register &amp; Login.
        /// </summary>
        public static string RegisterAndLogin {
            get {
                return ResourceManager.GetString("RegisterAndLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permission.
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Your Time.
        /// </summary>
        public static string SaveYourTime {
            get {
                return ResourceManager.GetString("SaveYourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is money. NetStarter can save your time and money by speeding up the initial development process..
        /// </summary>
        public static string SaveYourTimeDescription {
            get {
                return ResourceManager.GetString("SaveYourTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Email.
        /// </summary>
        public static string SendingEmail {
            get {
                return ResourceManager.GetString("SendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed With Latest Stable Framework Or Libraries.
        /// </summary>
        public static string SpecificationsDescription {
            get {
                return ResourceManager.GetString("SpecificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Admin Panel.
        /// </summary>
        public static string StandardAdminPanel {
            get {
                return ResourceManager.GetString("StandardAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Home Page.
        /// </summary>
        public static string StandardHomePage {
            get {
                return ResourceManager.GetString("StandardHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support from developer (Support policy applied).
        /// </summary>
        public static string Supportfromdeveloper {
            get {
                return ResourceManager.GetString("Supportfromdeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the following article.
        /// </summary>
        public static string TheFollowingArticle {
            get {
                return ResourceManager.GetString("TheFollowingArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To NetStarter.
        /// </summary>
        public static string ToNetStarter {
            get {
                return ResourceManager.GetString("ToNetStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Links.
        /// </summary>
        public static string UsefulLinks {
            get {
                return ResourceManager.GetString("UsefulLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various Charts.
        /// </summary>
        public static string VariousCharts {
            get {
                return ResourceManager.GetString("VariousCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various Form Controls.
        /// </summary>
        public static string VariousFormControls {
            get {
                return ResourceManager.GetString("VariousFormControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View More.
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetStarter.
        /// </summary>
        public static string WebAppTitle {
            get {
                return ResourceManager.GetString("WebAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you get.
        /// </summary>
        public static string Whatyouget {
            get {
                return ResourceManager.GetString("Whatyouget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Purchasing, You Will Get A Zip File Which Contains The Following.
        /// </summary>
        public static string WhatyougetDescription {
            get {
                return ResourceManager.GetString("WhatyougetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why NetStarter.
        /// </summary>
        public static string WhyNetStarter {
            get {
                return ResourceManager.GetString("WhyNetStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Project With User Management, Role Permission &amp; More.
        /// </summary>
        public static string WhyNetStarterLargeTitle {
            get {
                return ResourceManager.GetString("WhyNetStarterLargeTitle", resourceCulture);
            }
        }
    }
}
